### PR TITLE
Use C++11 ABI on Node.js 18.x+ on Linux

### LINKED ISSUE #6: Node v18 support
When adding support to my module to Node v18, I had the following error:

```
node: symbol lookup error: /home/matteo/repositories/synchronous-worker/build/Release/synchronous_worker.node: undefined symbol: _ZN4node17CreateEnvironmentEPNS_11IsolateDataEN2v85LocalINS2_7ContextEEERKSt6vectorISsSaISsEESA_NS_16EnvironmentFlags5FlagsENS_8ThreadIdESt10unique_ptrINS_21InspectorParentHandleESt14default_deleteISF_EE
```

Note I have this error only on Linux and not on Mac.

### PR DESCRIPTION
**Pull request by addaleax**
Fixes: https://github.com/addaleax/synchronous-worker/issues/6
Refs: https://github.com/nodejs/node/pull/36634

### CODE REVIEW

File: src/binding.cc [hunk 1]
```diff
@@ -1,6 +1,8 @@
+#include "node_version.h"
+
 // Node.js published binary compatibility
 #undef _GLIBCXX_USE_CXX11_ABI
-#ifdef __arm__
+#if defined(__arm__) || NODE_VERSION_AT_LEAST(18, 0, 0)
```
Comment (mcollina) [inline src/binding.cc:5]: Amazing, thanks!
